site_name: dlicudi.github.io
site_url: https://dlicudi.github.io/
repo_url: https://github.com/dlicudi/dlicudi.github.io
repo_name: dlicudi/dlicudi.github.io
plugins:
  - search
  - badges
  - tags
  - git-revision-date-localized:
      enable_creation_date: false
      fallback_to_build_date: true
  - git-committers:
      repository: dlicudi/cv
      branch: main
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs  
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - navigation.footer        
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/dlicudi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dlicudi
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/duanelicudi
    - icon: fontawesome/solid/paper-plane
      link: mailto:<dlicudi@gmail.com>


copyright: Copyright &copy; 2024 - 2025 Duane Licudi